# Place this file in staredit\briefing.ini to have map choices

# Controls with id -700 to -799 will be hidden in maps unless
# briefing.ini enables them. Can use other control ids too though.
[control:-700 choice:1]
name = Delivered in full
deaths 100 1 = 0 # Set deaths for unit (id) of (player normal ID) to = (int)

[control:-700 choice:2]
name = Used to transport allies
deaths 100 1 = 1 # Set deaths for unit (id) of (player normal ID) to = (int)
deaths 189 4 = 2 #oops not sure if this is even used :D
spawn 7 5806 1560 4
spawn 7 5771 1620 4
spawn 64 5597 1624 4
spawn 64 5591 1681 4

[control:-700 choice:3]
name = Used to bomb UED
deaths 100 1 = 2 # Set deaths for unit (id) of (player normal ID) to = (int)

# Label that stays hidden in other maps (Needs to be added in .ui.json ofc)
[control:-701]
name = Kel-Morian resources are...
